REFERENCE_GENOMES = {
    'test0': "GCAT",
    'test1': "GATACA",
    'test2': "AACCGGTT",
    'test3': "ACGTACGTACGTACGTACGTACGTACGTACGT",
    'test4': "TGCATGCATGCATGCA",
    'test5': "GACATCAGGGATCCAT"
}
